# Generated by Django 4.2.16 on 2024-10-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='popular',
        ),
    ]
