# Generated by Django 4.2.16 on 2024-10-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_destination_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_img',
        ),
    ]
