# Generated by Django 4.2.16 on 2024-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_category_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='destination_gallery/'),
        ),
    ]
