# Generated by Django 4.2.16 on 2024-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_imagegallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
