# Generated by Django 4.2.16 on 2024-11-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_alter_destination_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='caption',
        ),
    ]
