# Generated by Django 4.2.16 on 2024-11-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
