# Generated by Django 4.2.16 on 2024-11-03 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
