# Generated by Django 4.2.16 on 2024-11-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='accommodation',
            field=models.IntegerField(null=True),
        ),
    ]
