# Generated by Django 4.2.16 on 2024-11-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_room_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.room'),
        ),
    ]
