# Generated by Django 4.2.16 on 2024-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_travelpackage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
