# Generated by Django 4.2.16 on 2024-11-27 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_travelpackage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='TravelPackage_gallery')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='packages.travelpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
