# Generated by Django 4.2.16 on 2024-11-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_coupon'),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='destinations.destination'),
        ),
    ]
