# Generated by Django 4.2.16 on 2024-11-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('bookings', '0003_remove_booking_package_booking_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='packages.travelpackage'),
        ),
    ]
