# Generated by Django 4.2.16 on 2024-11-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_coupon_booking_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slug',
        ),
    ]
