# Generated by Django 4.2.16 on 2024-11-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_description',
            field=models.TextField(null=True),
        ),
    ]
